// <auto-generated />
namespace BugTrackingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class yew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yew));
        
        string IMigrationMetadata.Id
        {
            get { return "201908051149390_yew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
